name: commudle
description: Commudle UI

dependencies:
  simple_animations: ^1.3.3
  flutter:
    sdk: flutter

# flutter_launcher_icons: "^0.6.1"

# flutter_icons:
#   image_path: "images/commudle-logo.png" 
#   android: true
#   ios: true

flutter:
  uses-material-design: true

  assets:
    - images/commudle-logo.png